USE WAREHOUSE taxi_data;
USE DATABASE nyc_taxi_db;
USE SCHEMA raw;
LIST @taxi_data_stage;

CREATE OR REPLACE TABLE RAW.YELLOW_TAXI_TRIPS
USING TEMPLATE (
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
FROM TABLE(
INFER_SCHEMA(
LOCATION=>'@taxi_data_stage',
FILE_FORMAT=>'PARQUET_FORMAT'
)
)
);

DESC TABLE RAW.YELLOW_TAXI_TRIPS;

COPY INTO RAW.YELLOW_TAXI_TRIPS
FROM @taxi_data_stage
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT *
FROM RAW.YELLOW_TAXI_TRIPS
LIMIT 10;

DESC TABLE RAW.YELLOW_TAXI_TRIPS;